# fly.toml app configuration file generated for bloglistjfafso on 2023-11-18T06:40:54-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bloglistjfafso"
primary_region = "ord"

[deploy]
  release_command = "npm run build:ui"

[processes]
  app = "node index.js"

[build]
  [build.args]
    NODE_VERSION = "21.1.0"

[env]
  PORT = "8080"

[[services]]
internal_port = 8080
protocol = "tcp"
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.http_checks]]
interval = 10000
grace_period = "10s"
method = "get"
path = "/health"
protocol = "http"
timeout = 2000
tls_skip_verify = false
[services.http_checks.headers]

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"

[[services.http_service]]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]
