name: Periodic Health Check

on:
  schedule:
    - cron: '30 * * * *'

jobs:
  run_health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the URL
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://bloglistjfafso.fly.dev/
